### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by guidobouman** [Gideonnn/cordova-webpack-plugin#2]
Hi,

I'm using a vue-webpack scaffold with an index.html in the root. I've added the CordovaWebpackPlugin to my build env Webpack config.

This is my config:
```
    new CordovaWebpackPlugin({
      output: 'dist',                 /* Specify the output folder */
      config: 'cordova-config.xml',   /* The source config for cordova which will be copied to the output folder as 'config.xml' */
      index: './index.html',          /* The source index.html which will be copied to the <output folder>/www/ folder as 'index.html' */
      disabled: false                 /* (optional) Boolean value to conditionally run the plugin */
    })
```

But Cordova renders an empty page and there's no index.html in the platform www folder.

I've tried `index.html`, `./index.html`, `../index.html` to get the index.html from the root to copied along. The `../...` variant gave me a warning about not being able to find the index.html file.

**Comment by guidobouman** [comment]
Ok, moving the plugin to the production build step actually got my html & css inside Cordova.  But the console outputs an error that all external files (CSS & JS) can't be found, even though the paths are correct: they're in a `static/` folder, and the html file is pointing towards the right urls.

**Comment by guidobouman** [comment]
It seems like absolute urls (`/static/file.js`) don't work, but relative urls (`cordova.js`) do work.

**Comment by Gideonnn** [comment]
I think this has to do with how Webpack handles it's files and not the plugin itself, but I am not sure. I am really busy this weekend, I can check it out next week. Can you supply me the steps to reproduce the issue? Or you can send a PR to fix it, if you found a solution by now.
